# generated by datamodel-codegen:
#   filename:  submission.schema.json
#   timestamp: 2024-02-09T14:48:55+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Submission(BaseModel):
    id: Optional[str] = Field(None, description='Patient ID')
    align: Optional[str] = Field(None, description='Aligned lesion')
    ageDiagM: Optional[int] = Field(None, description='Age at Diagnosis in Months')
    ageDiagY: Optional[int] = Field(None, description='Age at Diagnosis in Years')
    ppsa: Optional[float] = Field(None, description='Presenting PSA at diagnosis')
    BxPreDiag: Optional[int] = Field(None, description='Biopsy before diagnosis')
    psaBx: Optional[float] = Field(None, description='PSA at Biopsy A')
    months_diag: Optional[int] = Field(
        None,
        alias='months.diag',
        description='Months that elapsed since prostate cancer diagnosis',
    )
    gleason: Optional[str] = Field(None, description='Gleason grade')
    mccl: Optional[int] = Field(None, description='Maximum Cancer Core Length in mm')
    ucl: Optional[str] = Field(None, description='UCL Definition')
    prvol: Optional[float] = Field(None, description='Prostate volume on MRI')
    side: Optional[str] = Field(None, description='Sampled area side (Left or Right)')
    zone: Optional[str] = Field(
        None, description='Sampled area zone (Peripheral, Transition, Both)'
    )
    loc: Optional[str] = Field(
        None, description='Sampled area location (Posterior, Anterior or combinations)'
    )
    level: Optional[str] = Field(
        None, description='Sampled area level (Base, Mid-gland, Apex or combinations)'
    )
    likert: Optional[int] = Field(None, description='Likert score of sampled MRI area')
    pirads: Optional[int] = Field(
        None, description='PI-RADSv2 score of sampled MRI area'
    )
    precise: Optional[int] = Field(
        None, description='PRECISE score of sampled MRI area (only for timepoint B)'
    )
    adcMean: Optional[float] = Field(
        None, description='Mean apparent diffusion coefficient of sampled MRI area'
    )
    adcn: Optional[float] = Field(
        None,
        description='Mean apparent diffusion coefficient of sampled MRI area (normalised by contralateral benign prostate ADC)',
    )
    adcu: Optional[float] = Field(
        None,
        description='Mean apparent diffusion coefficient of sampled MRI area (normalised by urine ADC)',
    )
    focality: Optional[str] = Field(None, description='Lesion focality')
    best: Optional[str] = Field(
        None, description='MRI sequence on which lesion is best seen'
    )
    bestVol: Optional[float] = Field(
        None, description='Volume of lesion on best sequence (ml)'
    )
    t2Vol: Optional[float] = Field(None, description='Lesion volume on T2 (ml)')
    Epi_Count: Optional[int] = Field(
        None,
        description='Total number of epithelial cells within all tissue areas on H&E',
    )
    Stroma_Count: Optional[int] = Field(
        None, description='Total number of stromal cells within all tissue areas on H&E'
    )
    Lymphocyte_Count: Optional[int] = Field(
        None, description='Total number of lymphocytes within all tissue areas on H&E'
    )
    Lymphocyte_Percentage: Optional[float] = Field(
        None, description='% of lymphocytes within all tissue areas on H&E'
    )
    Irani_Gscore: Optional[int] = Field(
        None,
        description='Irani score (number of lymphocytes in largest inflammatory cluster)',
    )
    Tissue_Area: Optional[float] = Field(None, description='Tissue area (square mm)')
    Epithelial_Area: Optional[float] = Field(
        None, description='Epithelial area (square mm)'
    )
    Stromal_Area: Optional[float] = Field(None, description='Stromal area (square mm)')
    Inflammatory_Area: Optional[float] = Field(
        None, description='Inflammation area (square mm)'
    )
    Epithelial_Area_Percentage: Optional[float] = Field(
        None, description='% epithelial area (epithelial area fraction)'
    )
    Stromal_Area_Percentage: Optional[float] = Field(
        None, description='% stromal area (stromal area fraction)'
    )
    Inflammatory_Area_Percentage: Optional[float] = Field(
        None, description='% inflammation area (inflammation area fraction)'
    )
    Epithelial_Stromal_Ratio: Optional[float] = Field(
        None, description='Epithelial area/Stromal area (square mm)'
    )
    Lumen_Area: Optional[float] = Field(
        None,
        description='Total area detected as lumen within all tissue areas (square mm)',
    )
    Lumen_Density: Optional[float] = Field(None, description='Lumen area/tissue area')
    Lumen_Density_Gland: Optional[float] = Field(
        None, description='Lumen area/epithelial area'
    )
    Annotated_Cancer_Area: Optional[float] = Field(
        None, description='Total area of cancer annotated by pathologist'
    )
    Normal_Area: Optional[float] = Field(
        None, description='Area classified as normal by classifier'
    )
    PIN_Area: Optional[float] = Field(
        None, description='Area classified as PIN by classifier'
    )
    Gleason_3_Area: Optional[float] = Field(
        None, description='Area classified as G3 by classifier'
    )
    Gleason_4_Area: Optional[float] = Field(
        None, description='Area classified as G4 by classifier'
    )
    Gleason_5_Area: Optional[float] = Field(
        None, description='Area classified as G5 or higher by classifier'
    )
    Gleason_Primary: Optional[int] = Field(
        None, description='Primary Gleason according to classifier'
    )
    Gleason_Secondary: Optional[int] = Field(
        None, description='Secondary Gleason according to classifier'
    )
    Grade_Group: Optional[int] = Field(
        None, description='Grade Group according to classifier'
    )
